name: lint-n-sast

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '*/1 * * * *' # every 1 min
    - cron: '*/3 * * * *' # every 3 min
    - cron: '*/5 * * * *' # every 5 min 
    - cron: '0 16 1 2 *'  # At 16:00 on day-of-month 1 and on Monday in February

  workflow_dispatch:

jobs:
  test1:
    # if: github.event.schedule != '*/3 * * * *'&&'*/1 * * * *'
    if: github.event.schedule == '*/3 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo "Hello"
        
  test2:
    # if: github.event.schedule != '*/5 * * * *'&&'*/3 * * * *'
    if: github.event.schedule == '*/5 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: echo "world"

  test3:
    # if: github.event.schedule != '*/1 * * * *'&&'*/5 * * * *'
    if: github.event.schedule == '*/1 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: test3
        run: echo "test3" 

  test4:
    if: github.event.schedule == '0 16 1 2 *'
    runs-on: ubuntu-latest
    steps:
      - name: test4
        run: echo "test4"       

  test-report:
    needs: test1
    runs-on: ubuntu-latest
    steps:
      - name: test-report
        run: echo "test-report"
