name: lint-n-sast

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

  workflow_dispatch:

jobs:
  lint-n-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker login
        run: echo "Hello"
