name: lint-n-sast

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
  schedule:
    - cron: '*/3 * * * *' # every 3 min
    - cron: '*/5 * * * *' # every 5 min 

  workflow_dispatch:

jobs:
  test1:
    if: github.event.schedule == '*/3 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Run docker login
        run: |
            echo "Hello"
        
  test2:
    if: github.event.schedule == '*/5 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Run docker login
        run: echo "world"
      
